#!/bin/bash
set -e

# Optimize site content
#
# Requires graphicsmagick and uglify.


headers_dir="static/images/headers"
header_width=720



echo adjusting header sizes:

for f in $(ls -1 ${headers_dir}/*.jpg)
do
  echo mogrify -resize $header_width "'$f'"
done | gm batch -echo on -



echo minifying js ...

uglify -s static/js/leoToCSV.en.js -o static/js/leoToCSV.en.min.js > /dev/null
uglify -s static/js/leoToCSV.de.js -o static/js/leoToCSV.de.min.js > /dev/null
